export const NoticeType = {
  INVITE_HOST: 1,
  INVITE_GUEST: 2,
  FRIEND_REQUEST: 3,
  FRIEND_REQUEST_ACCEPTED: 4,
  GUEST_REQUEST: 5,
  CERTIFICATE_DENIED: 6,
  HOST_REQUEST: 7,
  HOST_REQUEST_REJECTED: 8,
  HOST_REQUEST_ALL_ACCEPTED: 9,
  GUEST_REQUEST_REJECTED: 10,
};
